language: php

php:
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
  - php: nightly

env:
  - LARAVEL_VERSION=""
  - LARAVEL_VERSION="5.5"
  - LARAVEL_VERSION="5.6"
  - LARAVEL_VERSION="5.7"

install:
  - composer self-update --snapshot
  - travis/laravel.php
  - composer update

script:
  - vendor/bin/phpunit
  - tests/lint.sh
  - vendor/bin/composer-require-checker

jobs:
  include:
    - stage: coverage
      script:
        - vendor/bin/phpunit --coverage-clover=coverage.xml
        - bash <(curl -s https://codecov.io/bash)

git:
  depth: 5

group: travis_latest
