language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
  - php: nightly

env:
  - LARAVEL_VERSION=""
  - LARAVEL_VERSION="5.5"

install:
  - composer self-update --snapshot
  - travis/laravel.php
  - composer update

script:
  - vendor/bin/phpunit --coverage-clover=clover.xml
  - tests/lint.sh
  - vendor/bin/composer-require-checker

after_success:
  - vendor/bin/php-coveralls

git:
  depth: 5

dist: trusty
sudo: false
